version: "3.9"

services:
  backend:
    build:
      context: ./flask
      dockerfile: Dockerfile
    container_name: flask-backend
    ports:
      - "5000:5000"
    networks:
      - internal_net
    restart: unless-stopped
    environment:
      - FRONIUS_IP=<Enter your Fronius IP here>

  frontend:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: web-frontend
    ports:
      - "8080:80"
    networks:
      - internal_net
    restart: unless-stopped
    depends_on:
      - backend
